LongoMatch/longomatch-core

LongoMatch.GUI/Gui/Menu/PlaysMenu.cs
LongoMatch.GUI/Gui/TreeView/ListTreeViewBase.cs
LongoMatch.GUI/Gui/TreeView/PlayersTreeView.cs
LongoMatch.GUI/Gui/TreeView/PlaysTreeView.cs
LongoMatch.GUI/Gui/TreeView/TreeViewHelpers.cs
LongoMatch.GUI/LongoMatch.GUI.csproj

With a right click on an EventType or a Player a new option to add
all the events in this Player or EventType to a playlist

Add an option to add cateogory and player events to a playlist

---

LongoMatch.GUI/Gui/Component/ToggleTopBar.cs
LongoMatch.Services/PlayerController.cs

Now it will pause the player if it's playing and is set to false.

Modify the Active behaviour

---

LongoMatch.Drawing/Canvas.cs

Add new Property to Timerule to ignore clicks

---

LongoMatch.GUI/Gui/Panel/WelcomePanel.cs
LongoMatch.GUI/gtk-gui/LongoMatch.Gui.Panel.ProjectsManagerPanel.cs
LongoMatch.GUI/gtk-gui/LongoMatch.Gui.Panel.SportsTemplatesPanel.cs
LongoMatch.GUI/gtk-gui/LongoMatch.Gui.Panel.TeamsTemplatesPanel.cs
LongoMatch.GUI/gtk-gui/gui.stetic

Changed icons order in managers panels to
new - import - save - export -delete

Add alignment to fix the welcome panel icon spacing

---

LongoMatch.Drawing/CanvasObjects/Dashboard/TimerObject.cs

clicks on it in Edit Dashboard mode.

Fix the problem of starting or stopping a timer event when the user

---

LongoMatch.Core/Store/MediaFileSet.cs
LongoMatch.Services/PlayerController.cs
Tests/Core/Store/TestMediaFileSet.cs
Tests/Services/TestPlayerController.cs

Add a method in MediaFileSet to check modified filepaths

LON-539#2 BugFix

---

LongoMatch.Drawing.Cairo/Surface.cs

Revert to the surface copy to file and read from from pixbuf

Fix display of event's drawings

---

LongoMatch.GUI/Gui/Panel/SportsTemplatesPanel.cs

- Copy correctly the old dashboard

LON-745: Crash when I delete a dashboard

---

LongoMatch.Services/PlayerController.cs

-If not ready to seek recieved prevent changing playback states
-Now when presentation playback arrives to the last element it starts
again to 00:00 in paused state.

LON-521#2 - Fixes Some bad behaviours in player controller

---

LongoMatch.DB/FileStorage.cs
LongoMatch.Drawing/CanvasObjects/Teams/PlayersTaggerObject.cs
Tests/Integration/TestPostGameAnalysis.cs

LMA-122: Add a helper function to retrieve templates using a Stream

---

LongoMatch.Addins/AddinsManager.cs
LongoMatch.Core/Interfaces/GUI/IAnalysisWindow.cs
LongoMatch.GUI/Gui/Component/FakeAnalysisComponent.cs
LongoMatch.GUI/Gui/Panel/NewProjectPanel.cs
LongoMatch.GUI/Gui/Panel/OpenProjectPanel.cs
LongoMatch.GUI/Gui/Panel/PreferencesPanel.cs
LongoMatch.GUI/Gui/Panel/ProjectsManagerPanel.cs
LongoMatch.GUI/Gui/Panel/SportsTemplatesPanel.cs
LongoMatch.GUI/Gui/Panel/TeamsTemplatesPanel.cs
LongoMatch/LongoMatch.csproj
LongoMatch/Main.cs
Tests/Integration/TestDatabaseMigrationV0.cs
Tests/Integration/TestPostGameAnalysis.cs
Tests/Setup.cs
tools/ide_linux.sh
tools/ide_osx.sh

* Fix tests
* Implement Dispose for IView implementors
* Update Xamarin scripts

Ra 89 - fixes

---

LongoMatch.DB/FodyWeavers.xml
LongoMatch.DB/LongoMatch.DB.Net45.csproj
LongoMatch.DB/ModuleInitializer.cs
LongoMatch.DB/packages.config
LongoMatch.Services/LongoMatch.Services.Net45.csproj
LongoMatch.Services/packages.config
Tests/Tests.csproj
Tests/packages.config
build/build_env.mk

Update to Couchbase 1.3 - VAS-24

---

LongoMatch.GUI/Gui/Panel/NewProjectPanel.cs
LongoMatch.Services/State/NewProjectState.cs

Also check for null before disposing elements

Fix New Project panel creation in Longomatch

---

LongoMatch.Services/Controller/LMEventsController.cs
LongoMatch.Services/State/FakeLiveAnalysisState.cs
LongoMatch.Services/State/LiveProjectAnalysisState.cs
LongoMatch.Services/State/ProjectAnalysisState.cs
Tests/State/TestFakeLiveProjectAnalysisState.cs
Tests/State/TestLiveProjectAnalysisState.cs
Tests/Tests.csproj
Tests/Utils.cs

AnalysisState should copy the model not the VM since it is disposed
Currentime is initialised when the dashboardVM is created
CapturerTick is checked by the TaggingController to update the CurrentTime of the VM.

Fake and live projects error when click button and capturer not started

---

LongoMatch.Services/Controller/TeamsController.cs

Message is taken from Longomatch release version

LON-980: Add a message for saving a static team dialog

---

LongoMatch.GUI/Gui/GUIToolkit.cs
LongoMatch.GUI/gtk-gui/LongoMatch.Gui.Component.SynchronizationWidget.cs
LongoMatch.GUI/gtk-gui/gui.stetic
LongoMatch.Services/State/ProjectAnalysisState.cs

Created the PR on behalf on @ylatuya

Adapt to new changes in the VideoPlayerView

---

LongoMatch.Core/ViewModel/LMTimelineVM.cs

Filters are not working properly were hiding some events in the tree view

Fix open projects not display all events

---

LongoMatch.GUI/gtk-gui/LongoMatch.Gui.Component.DashboardWidget.cs
LongoMatch.GUI/gtk-gui/gui.stetic

Fix dashboard editor buttons relief.

---

LongoMatch.GUI/Gui/Panel/TeamsTemplatesPanel.cs

Like it's done for static dashboards

Disable name edition for static teams

---

LongoMatch.Services/State/FakeLiveAnalysisState.cs
LongoMatch.Services/State/LMStateHelper.cs
Tests/State/TestFakeLiveProjectAnalysisState.cs
Tests/State/TestLMStateHelper.cs
Tests/State/TestLiveProjectAnalysisState.cs

Fix transition from new to analysis + record enable

FakeAnalysis Fixes

---

LongoMatch.GUI/Gui/Panel/NewProjectPanel.cs
LongoMatch.Services/State/NewProjectState.cs
LongoMatch.Services/ViewModel/NewProjectVM.cs
Tests/Services/ViewModel/TestNewProjectVM.cs
Tests/State/TestNewProjectState.cs
Tests/State/TestProjectsManagerState.cs
Tests/Tests.csproj

Use this collections to fill the lists in NewProjectPanel

Add Dashboards and teams Limited Collections to NewProjectVM

---

LongoMatch.Core/Store/LMProject.cs
LongoMatch.Drawing/Widgets/ProjectLocationsTaggerView.cs
LongoMatch.GUI/Gui/Component/NotesWidget.cs
LongoMatch.GUI/Gui/Component/PlayListWidget.cs
LongoMatch.GUI/Gui/Component/PlayersListTreeWidget.cs
LongoMatch.GUI/Gui/Component/PlaysListTreeWidget.cs
LongoMatch.GUI/Gui/Component/PlaysPositionViewer.cs
LongoMatch.GUI/Gui/Dialog/PlayEditor.cs
LongoMatch.GUI/Gui/Menu/EventTypeMenu.cs
LongoMatch.GUI/Gui/Menu/PlayerMenu.cs
LongoMatch.GUI/Gui/Menu/PlaylistElementMenu.cs
LongoMatch.GUI/Gui/Menu/SportsPlaysMenu.cs
LongoMatch.GUI/Gui/TreeView/LMTimelineEventsTreeView.cs
LongoMatch.GUI/Gui/TreeView/ListTreeViewBase.cs
LongoMatch.GUI/Gui/TreeView/PlayersTreeView.cs
LongoMatch.GUI/Gui/TreeView/PlaysTreeView.cs
LongoMatch.GUI/Gui/TreeView/TeamTimelineEventsTreeView.cs
LongoMatch.Services/Controller/EventEditorController.cs
LongoMatch.Services/Controller/LMEventsController.cs
LongoMatch.Services/Controller/LMTaggingController.cs
LongoMatch.Services/Controller/LMTeamTaggerController.cs
LongoMatch.Services/Controller/PlayEditorController.cs
LongoMatch.Services/ViewModel/PlayEditorVM.cs
Tests/Controller/TestLMEventsController.cs
Tests/Controller/TestPlayEditorController.cs
Tests/Controller/TestPlaylistController.cs
Tests/Core/ViewModel/TestForwarderPlaylistElementsVM.cs
Tests/Integration/TestPostGameAnalysis.cs
Tests/Services/TestEventEditorService.cs
Tests/Services/ViewModel/TestPlayEditorVM.cs

Reverts LongoMatch/longomatch-core#367

Revert "VAS 87 - Migrate events about TimelineEvent to VM"

---

Tests/Core/ViewModel/TestLMProjectVM.cs

The Edited property returns whether the model has been modified
